[pytest]
addopts = -s -v --alluredir=./report/temp --clean-alluredir

testpaths = ./testCases

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    last
    second
    first
    P1
    P2
    P3
